# This file was generated by GoReleaser. DO NOT EDIT.
cask "woof" do
  name "woof"
  desc "Datadog CLI tool"
  homepage "https://github.com/gplassard/woof"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "woof"

  on_macos do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_x86_64.tar.gz"
      sha256 "d3dcea6da7dcd32c23bb10acaab861f9efd2a23a64994ed73fb16708df5520eb"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_arm64.tar.gz"
      sha256 "b0ef4236e05b407b31cc0dca550d1d388c4656bba08be8bcb85bbed185149174"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_x86_64.tar.gz"
      sha256 "d422c506e6737ff5c6e36fe83f15160f5a22b3a1952cff0827a682bd374ab39a"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_arm64.tar.gz"
      sha256 "2578c88f6da34dcec7f29d67a3b0d5f5e1a0496f3e780a39879fe50951241f78"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/woof"]
    end
  end

  # No zap stanza required
end
