# This file was generated by GoReleaser. DO NOT EDIT.
cask "woof" do
  name "woof"
  desc "Datadog CLI tool"
  homepage "https://github.com/gplassard/woof"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "woof"

  on_macos do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_x86_64.tar.gz"
      sha256 "ca010ab8d73f1f0146dd12fd4d23dbe45388c9ce5a9e8f9468388666bd7ef34e"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_arm64.tar.gz"
      sha256 "f15de998c7b4cc5c4a2e4b841852e9412410197758b72b70842e8f5abe7f358d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_x86_64.tar.gz"
      sha256 "ae6489bf82b3668e1d09ce8173332d518b4330ac9e1e1933f6bd6bf68da97c0b"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_arm64.tar.gz"
      sha256 "90dccde0f1ab74fe400bce5bb925fbd7f949cf27ab55132f2b8e5d20ab9b5966"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/woof"]
    end
  end

  # No zap stanza required
end
