# This file was generated by GoReleaser. DO NOT EDIT.
cask "woof" do
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_x86_64.tar.gz"
      sha256 "83e9018c7e5c7e5ac44e76a98ae1ab6e08ff48d9c3415dc86f7f8386bb97597e"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_arm64.tar.gz"
      sha256 "6e8d79ce29ffaf62812b93de8a93550c79cb58c08cd436b607a0a5bbca389241"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_x86_64.tar.gz"
      sha256 "50d5f50066afc28892c2e38dcba6c6e412b4f26e58d0b3d06fd649143c253e2f"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_arm64.tar.gz"
      sha256 "06e6db0f469a17143ac1c69a8367ff816483d8b6cabf95b8c0854656e1ec4fc8"
    end
  end

  name "woof"
  desc "Datadog CLI tool"
  homepage "https://github.com/gplassard/woof"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "woof"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/woof"]
    end
  end

  # No zap stanza required

end
