# This file was generated by GoReleaser. DO NOT EDIT.
cask "woof" do
  name "woof"
  desc "Datadog CLI tool built with Go"
  homepage "https://github.com/gplassard/woof"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "woof"

  on_macos do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_x86_64.tar.gz"
      sha256 "e26ec0fc70d9f7fa960939225f8a5af779efe25ab8b86ecb29248ce084af01a8"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Darwin_arm64.tar.gz"
      sha256 "d791afc2191a0db888f7abf4b89c6c91da195d572b2c0cab17666ce53a51209b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_x86_64.tar.gz"
      sha256 "ffe717e48ef6ee473fb2f57ff00a1ab971a0d8192cbf2d8d832e53e4f8a8daea"
    end
    on_arm do
      url "https://github.com/gplassard/woof/releases/download/v#{version}/woof_Linux_arm64.tar.gz"
      sha256 "0c26b9936444343fa1f3c4c1fe460447b2b67d036cf58471fcfee1421c1eab74"
    end
  end

  # No zap stanza required
end
